// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC8Sp1tejWZ1zVCZunN5NnwuM__weNTDhI',
    appId: '1:29559896656:web:c07fc11d8b42f3dd6baf55',
    messagingSenderId: '29559896656',
    projectId: 'gympad-e44fc',
    authDomain: 'gympad-e44fc.firebaseapp.com',
    storageBucket: 'gympad-e44fc.firebasestorage.app',
    measurementId: 'G-HPXHJBM6VP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCdFgEPuDFzUDmkwfKqvfNMRx1Rs-dMiCo',
    appId: '1:29559896656:android:6af18b9aa96e729d6baf55',
    messagingSenderId: '29559896656',
    projectId: 'gympad-e44fc',
    storageBucket: 'gympad-e44fc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD9Wu-nrC2nJAXjL510ZoIzgiSppnduolI',
    appId: '1:29559896656:ios:b5324f8c146d92b36baf55',
    messagingSenderId: '29559896656',
    projectId: 'gympad-e44fc',
    storageBucket: 'gympad-e44fc.firebasestorage.app',
    iosBundleId: 'com.gympad.gympad',
  );

}